"""Normalised intermediate representations for ingested report data.

These types flow between the ingest service (which produces them from raw
JSON) and the detection service (which reads them for anomaly computation).
They live in a separate module to avoid circular imports between the two
services.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from uuid import UUID


@dataclass(frozen=True)
class NormalisedHandle:
    """A single handle extracted and normalised from the raw report."""

    topic: str
    outcome: str
    latency_ms: float | None
    budget_ms: float | None
    attempts: int
    matcher_description: str
    diagnosis_kind: str | None
    over_budget: bool


@dataclass(frozen=True)
class NormalisedScenario:
    """A single scenario extracted from the raw report."""

    test_nodeid: str
    name: str
    correlation_id: str | None
    outcome: str
    duration_ms: float
    completed_normally: bool
    handles: tuple[NormalisedHandle, ...]


@dataclass(frozen=True)
class NormalisedReport:
    """The intermediate representation between raw JSON and database rows.

    Produced by ``normalise_report()``, consumed by the repository
    write methods and the detection service.
    """

    # Run metadata
    started_at: datetime
    finished_at: datetime
    duration_ms: float
    environment: str | None
    transport: str
    branch: str | None
    git_sha: str | None
    hostname: str | None
    harness_version: str | None
    reporter_version: str | None
    python_version: str | None
    project_name: str | None

    # Totals
    total_tests: int
    total_passed: int
    total_failed: int
    total_errored: int
    total_skipped: int
    total_slow: int

    # Exploded data
    scenarios: list[NormalisedScenario]

    @property
    def handle_count(self) -> int:
        return sum(len(s.handles) for s in self.scenarios)

    @property
    def scenario_count(self) -> int:
        return len(self.scenarios)

    @property
    def topics(self) -> set[str]:
        """Distinct topics across all handles."""
        return {h.topic for s in self.scenarios for h in s.handles}


@dataclass(frozen=True)
class NewAnomaly:
    """An anomaly to be persisted.  Does not have ``id`` or ``detected_at``
    -- those are generated by the database on insert."""

    tenant_id: UUID
    run_id: UUID
    topic: str
    detection_method: str  # "rolling_baseline", "budget_violation", "outcome_shift"
    metric: str  # "p95_ms", "budget_violation_pct", "timeout_rate"
    current_value: float
    baseline_value: float
    baseline_stddev: float
    change_pct: float
    severity: str  # "warning", "critical"


def normalise_report(report: object) -> NormalisedReport:
    """Extract and normalise fields from the raw report into the
    intermediate representation.

    Accepts any object with ``run`` (dict) and ``tests`` (list[dict])
    attributes -- typically an ``IngestRequest``.

    Derives:
    - ``over_budget`` from ``handle.diagnosis.kind == "over_budget"``
    - ``diagnosis_kind`` from ``handle.diagnosis.kind``
    - Flattens the test->scenario->handle hierarchy
    """
    run = report.run  # type: ignore[attr-defined]
    tests = report.tests  # type: ignore[attr-defined]
    totals = run["totals"]

    scenarios: list[NormalisedScenario] = []
    for test in tests:
        for scenario_dict in test.get("scenarios", []):
            handles: list[NormalisedHandle] = []
            for h in scenario_dict.get("handles", []):
                diagnosis = h.get("diagnosis") or {}
                diagnosis_kind = diagnosis.get("kind")
                handles.append(
                    NormalisedHandle(
                        topic=h["topic"],
                        outcome=h["outcome"],
                        latency_ms=h.get("latency_ms"),
                        budget_ms=h.get("budget_ms"),
                        attempts=h.get("attempts", 0),
                        matcher_description=h.get("matcher_description", ""),
                        diagnosis_kind=diagnosis_kind,
                        over_budget=diagnosis_kind == "over_budget",
                    )
                )
            scenarios.append(
                NormalisedScenario(
                    test_nodeid=test["nodeid"],
                    name=scenario_dict["name"],
                    correlation_id=scenario_dict.get("correlation_id"),
                    outcome=scenario_dict["outcome"],
                    duration_ms=scenario_dict["duration_ms"],
                    completed_normally=scenario_dict["completed_normally"],
                    handles=tuple(handles),
                )
            )

    return NormalisedReport(
        started_at=datetime.fromisoformat(run["started_at"]),
        finished_at=datetime.fromisoformat(run["finished_at"]),
        duration_ms=run["duration_ms"],
        environment=run.get("environment"),
        transport=run["transport"],
        branch=run.get("git_branch"),
        git_sha=run.get("git_sha"),
        hostname=run.get("hostname"),
        harness_version=run.get("harness_version"),
        reporter_version=run.get("reporter_version"),
        python_version=run.get("python_version"),
        project_name=run.get("project_name"),
        total_tests=totals["total"],
        total_passed=totals["passed"],
        total_failed=totals["failed"],
        total_errored=totals["errored"],
        total_skipped=totals["skipped"],
        total_slow=totals["slow"],
        scenarios=scenarios,
    )
