"""Normalised intermediate representations for ingested report data.

These types flow between the ingest service (which produces them from raw
JSON) and the detection service (which reads them for anomaly computation).
They live in a separate module to avoid circular imports between the two
services.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from uuid import UUID


@dataclass(frozen=True)
class NormalisedHandle:
    """A single handle extracted and normalised from the raw report."""

    topic: str
    outcome: str
    latency_ms: float | None
    budget_ms: float | None
    attempts: int
    matcher_description: str
    diagnosis_kind: str | None
    over_budget: bool
    # PRD-012: per-handle transport for Stage scenarios. None for
    # single-Harness handles. Flowed through to
    # `handle_measurements.transport` by the repository.
    transport: str | None = None


@dataclass(frozen=True)
class NormalisedTimelineEvent:
    """A single timeline event extracted and normalised from
    `scenario.timeline[]` (PRD-013, schema v1.3).

    Mirrors the v1.3 JSON shape: mandatory `time` (parsed from
    `wall_clock`), `action`, `detail`, `offset_ms` plus optional
    `topic` / `transport` / `logical_topic` / `source`. Flowed through
    to `timeline_events.{column}` by `RunRepository.copy_timeline_events`.
    """

    time: datetime
    offset_ms: float
    action: str
    detail: str
    topic: str | None = None
    transport: str | None = None
    logical_topic: str | None = None
    source: str | None = None


@dataclass(frozen=True)
class NormalisedScenario:
    """A single scenario extracted from the raw report."""

    test_nodeid: str
    name: str
    correlation_id: str | None
    outcome: str
    duration_ms: float
    completed_normally: bool
    handles: tuple[NormalisedHandle, ...]
    # PRD-013 §1.6: optional with default to keep backward-compat with
    # test fixtures constructing NormalisedScenario directly. v1.0/v1.1
    # reports populate an empty tuple; v1.2/v1.3 Stage reports carry
    # captured events.
    timeline: tuple[NormalisedTimelineEvent, ...] = ()


@dataclass(frozen=True)
class NormalisedReport:
    """The intermediate representation between raw JSON and database rows.

    Produced by ``normalise_report()``, consumed by the repository
    write methods and the detection service.
    """

    # Run metadata
    started_at: datetime
    finished_at: datetime
    duration_ms: float
    environment: str | None
    # PRD-012: `transport` is now nullable (Stage-only or mixed runs);
    # `transports` carries the sorted union when populated. Repository
    # writes `transport` to `runs.transport` (column relaxed to nullable
    # by migration `003_prd012_stage_transports.py`); `transports` to
    # `runs.transports`.
    transport: str | None
    branch: str | None
    git_sha: str | None
    hostname: str | None
    harness_version: str | None
    reporter_version: str | None
    python_version: str | None
    project_name: str | None

    # Totals
    total_tests: int
    total_passed: int
    total_failed: int
    total_errored: int
    total_skipped: int
    total_slow: int

    # Exploded data
    scenarios: list[NormalisedScenario]

    # PRD-012: optional with default to keep backward compatibility
    # with test fixtures constructing NormalisedReport directly.
    transports: list[str] | None = None

    @property
    def handle_count(self) -> int:
        return sum(len(s.handles) for s in self.scenarios)

    @property
    def scenario_count(self) -> int:
        return len(self.scenarios)

    @property
    def topics(self) -> set[str]:
        """Distinct topics across all handles."""
        return {h.topic for s in self.scenarios for h in s.handles}


@dataclass(frozen=True)
class NewAnomaly:
    """An anomaly to be persisted.  Does not have ``id`` or ``detected_at``
    -- those are generated by the database on insert."""

    tenant_id: UUID
    run_id: UUID
    topic: str
    detection_method: str  # "rolling_baseline", "budget_violation", "outcome_shift"
    metric: str  # "p95_ms", "budget_violation_pct", "timeout_rate"
    current_value: float
    baseline_value: float
    baseline_stddev: float
    change_pct: float
    severity: str  # "warning", "critical"


def normalise_report(report: object) -> NormalisedReport:
    """Extract and normalise fields from the raw report into the
    intermediate representation.

    Accepts any object with ``run`` (dict) and ``tests`` (list[dict])
    attributes -- typically an ``IngestRequest``.

    Derives:
    - ``over_budget`` from ``handle.diagnosis.kind == "over_budget"``
    - ``diagnosis_kind`` from ``handle.diagnosis.kind``
    - Flattens the test->scenario->handle hierarchy
    """
    run = report.run  # type: ignore[attr-defined]
    tests = report.tests  # type: ignore[attr-defined]
    totals = run["totals"]

    scenarios: list[NormalisedScenario] = []
    for test in tests:
        for scenario_dict in test.get("scenarios", []):
            # PRD-012 contract: a Stage scenario (signalled by the
            # `stage` block) carries per-handle `transport` on every
            # handle. Validate the invariant up-front so the COPY
            # protocol does not later attempt to write NULL into the
            # NOT-NULL `handle_measurements.transport` column with an
            # opaque IntegrityError.
            is_stage_scenario = scenario_dict.get("stage") is not None
            handles: list[NormalisedHandle] = []
            for h in scenario_dict.get("handles", []):
                diagnosis = h.get("diagnosis") or {}
                diagnosis_kind = diagnosis.get("kind")
                handle_transport = h.get("transport")
                if is_stage_scenario and handle_transport is None:
                    raise ValueError(
                        f"Stage handle on topic {h.get('topic')!r} in scenario "
                        f"{scenario_dict.get('name')!r} has no `transport` field; "
                        "PRD-012 §1.1 requires every Stage handle to carry one."
                    )
                handles.append(
                    NormalisedHandle(
                        topic=h["topic"],
                        outcome=h["outcome"],
                        latency_ms=h.get("latency_ms"),
                        budget_ms=h.get("budget_ms"),
                        attempts=h.get("attempts", 0),
                        matcher_description=h.get("matcher_description", ""),
                        diagnosis_kind=diagnosis_kind,
                        over_budget=diagnosis_kind == "over_budget",
                        transport=handle_transport,
                    )
                )
            # PRD-013 §1.6: extract timeline events. v1.0/v1.1 reports
            # have an empty list (deferral marker); v1.2/v1.3 reports
            # carry the captured events. The normaliser parses
            # `wall_clock` into a tz-aware datetime; the v1.3 schema
            # validates the ISO format upstream.
            timeline_events: list[NormalisedTimelineEvent] = []
            for entry in scenario_dict.get("timeline", []):
                timeline_events.append(
                    NormalisedTimelineEvent(
                        time=datetime.fromisoformat(entry["wall_clock"]),
                        offset_ms=entry["offset_ms"],
                        action=entry["action"],
                        detail=entry["detail"],
                        topic=entry.get("topic"),
                        transport=entry.get("transport"),
                        logical_topic=entry.get("logical_topic"),
                        source=entry.get("source"),
                    )
                )
            scenarios.append(
                NormalisedScenario(
                    test_nodeid=test["nodeid"],
                    name=scenario_dict["name"],
                    correlation_id=scenario_dict.get("correlation_id"),
                    outcome=scenario_dict["outcome"],
                    duration_ms=scenario_dict["duration_ms"],
                    completed_normally=scenario_dict["completed_normally"],
                    handles=tuple(handles),
                    timeline=tuple(timeline_events),
                )
            )

    return NormalisedReport(
        started_at=datetime.fromisoformat(run["started_at"]),
        finished_at=datetime.fromisoformat(run["finished_at"]),
        duration_ms=run["duration_ms"],
        environment=run.get("environment"),
        transport=run.get("transport"),
        transports=run.get("transports"),
        branch=run.get("git_branch"),
        git_sha=run.get("git_sha"),
        hostname=run.get("hostname"),
        harness_version=run.get("harness_version"),
        reporter_version=run.get("reporter_version"),
        python_version=run.get("python_version"),
        project_name=run.get("project_name"),
        total_tests=totals["total"],
        total_passed=totals["passed"],
        total_failed=totals["failed"],
        total_errored=totals["errored"],
        total_skipped=totals["skipped"],
        total_slow=totals["slow"],
        scenarios=scenarios,
    )
