


















mock_endpoints:
  - "mock://localhost"



nats_servers:
  - "nats://localhost:4222"
  - "nats://127.0.0.1:4222"
  - "nats://nats:4222"
  - "nats://localhost:4223"
  - "nats://127.0.0.1:4223"



kafka_brokers:
  - "localhost:9092"
  - "127.0.0.1:9092"
  - "kafka:9092"





amqp_brokers:
  - "amqp://guest:guest@localhost:5672/"
  - "amqp://guest:guest@127.0.0.1:5672/"
  - "amqp://guest:guest@rabbitmq:5672/"


redis_servers:
  - "redis://localhost:6379/0"
  - "redis://127.0.0.1:6379/0"
  - "redis://redis:6379/0"
